-- Run this script in the Supabase SQL Editor to set up the leaderboard table.
-- It is safe to rerun against an existing database.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score bigint not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.leaderboard
  add column if not exists is_multiplayer boolean;

alter table public.leaderboard
  alter column is_multiplayer set default false;

alter table public.leaderboard enable row level security;

grant select, insert on public.leaderboard to anon;
grant select, insert on public.leaderboard to authenticated;

do $$
declare
  leaderboard_id_seq text;
begin
  leaderboard_id_seq := pg_get_serial_sequence('public.leaderboard', 'id');

  if leaderboard_id_seq is not null then
    execute format('grant usage, select on sequence %s to anon', leaderboard_id_seq);
    execute format('grant usage, select on sequence %s to authenticated', leaderboard_id_seq);
  end if;
end $$;

create index if not exists idx_leaderboard_score_desc
  on public.leaderboard (score desc, created_at asc);

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'leaderboard'
      and policyname = 'Enable read access for all users'
  ) then
    create policy "Enable read access for all users"
      on public.leaderboard
      for select
      to anon, authenticated
      using (true);
  else
    alter policy "Enable read access for all users"
      on public.leaderboard
      to anon, authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'leaderboard'
      and policyname = 'Enable insert access for all users'
  ) then
    create policy "Enable insert access for all users"
      on public.leaderboard
      for insert
      to anon, authenticated
      with check (true);
  else
    alter policy "Enable insert access for all users"
      on public.leaderboard
      to anon, authenticated
      with check (true);
  end if;
end $$;
