-- Run this script in the Supabase SQL Editor to setup your leaderboard

-- 1. Create the table
create table leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
-- This is important to ensure your database is secure by default
alter table leaderboard enable row level security;

-- 3. Create Policies
-- Allow anyone (public/anon key) to READ the leaderboard
create policy "Enable read access for all users" 
on leaderboard for select 
using (true);

-- Allow anyone (public/anon key) to INSERT a new score
create policy "Enable insert access for all users" 
on leaderboard for insert 
with check (true);

-- Optional: If you want to prevent users from modifying/deleting scores:
-- Do NOT create update/delete policies for the 'anon' role.
