-- Run this script in the Supabase SQL Editor to setup your leaderboard
-- =====================================================
-- LEADERBOARD TABLE (for single and multiplayer scores)
-- =====================================================

-- 1. Create the leaderboard table (if it doesn't exist)
create table if not exists leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add is_multiplayer column if it doesn't exist (for existing tables)
do $$ 
begin
  if not exists (select 1 from information_schema.columns 
                 where table_name = 'leaderboard' and column_name = 'is_multiplayer') then
    alter table leaderboard add column is_multiplayer boolean default false;
  end if;
end $$;

-- 3. Enable Row Level Security (RLS) for leaderboard
alter table leaderboard enable row level security;

-- 4. Create Policies for leaderboard (drop first if exists to avoid conflicts)
drop policy if exists "Enable read access for all users" on leaderboard;
create policy "Enable read access for all users" 
on leaderboard for select 
using (true);

drop policy if exists "Enable insert access for all users" on leaderboard;
create policy "Enable insert access for all users" 
on leaderboard for insert 
with check (true);

-- =====================================================
-- MULTIPLAYER SUPPORT - Game Rooms Table
-- =====================================================

-- 5. Create the game_rooms table for multiplayer
create table if not exists game_rooms (
  id uuid primary key default gen_random_uuid(),
  room_code text unique not null,
  host_id text not null,
  guest_id text,
  host_character text default 'male',
  guest_character text,
  status text default 'waiting' check (status in ('waiting', 'playing', 'finished')),
  team_score bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Enable Row Level Security (RLS) for game_rooms
alter table game_rooms enable row level security;

-- 7. Create Policies for game_rooms (drop first if exists)
drop policy if exists "Enable read access for game rooms" on game_rooms;
create policy "Enable read access for game rooms" 
on game_rooms for select 
using (true);

drop policy if exists "Enable insert access for game rooms" on game_rooms;
create policy "Enable insert access for game rooms" 
on game_rooms for insert 
with check (true);

drop policy if exists "Enable update access for game rooms" on game_rooms;
create policy "Enable update access for game rooms" 
on game_rooms for update 
using (true);

drop policy if exists "Enable delete access for game rooms" on game_rooms;
create policy "Enable delete access for game rooms" 
on game_rooms for delete 
using (true);

-- 8. Enable Supabase Realtime for game_rooms table
-- This allows real-time subscriptions for multiplayer sync
do $$
begin
  alter publication supabase_realtime add table game_rooms;
exception when duplicate_object then
  null; -- already added
end $$;

-- 9. Create indexes for faster lookups (if not exists)
create index if not exists idx_game_rooms_room_code on game_rooms(room_code);
create index if not exists idx_game_rooms_status on game_rooms(status);

-- 10. Function to auto-update the updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- 11. Trigger to auto-update updated_at on game_rooms (drop first if exists)
drop trigger if exists update_game_rooms_updated_at on game_rooms;
create trigger update_game_rooms_updated_at
  before update on game_rooms
  for each row
  execute function update_updated_at_column();

-- 12. Function to cleanup old/stale rooms (optional, run periodically)
create or replace function cleanup_old_rooms()
returns void as $$
begin
  delete from game_rooms 
  where (status = 'waiting' and created_at < now() - interval '1 hour')
     or (status = 'finished' and updated_at < now() - interval '10 minutes');
end;
$$ language plpgsql;
